/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.2.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    base
}

tasks.build {
    dependsOn("build53", "buildUltraWide")
}

tasks.register<Zip>("build53") {
    archiveBaseName.set("Fancy Warp Menu Build 53")
    destinationDirectory.set(layout.buildDirectory)
    from(layout.projectDirectory.dir("src/Fancy Warp Menu Build 53"))
    filesMatching("pack.mcmeta") {
        expand("modVersion" to project.properties["fancyWarpMenuVersion"])
    }
}

tasks.register<Zip>("buildUltraWide") {
    archiveBaseName.set("Fancy Warp Menu UltraWide")
    destinationDirectory.set(layout.buildDirectory)
    from(layout.projectDirectory.dir("src/Fancy Warp Menu UltraWide"))
    filesMatching("pack.mcmeta") {
        expand("modVersion" to project.properties["fancyWarpMenuVersion"])
    }
}
